name: Deploy to GitHub pages

on:
  push:
    branches:
      - main
      - TiNa
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  Frontend:
    name: Exercice
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repo
        uses: actions/checkout@v4

      - name : Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: fix lint
        run: npm run lint:fix

      - name: Run Linter
        run: npm run lint

      - name: Run Test
        run: npm run test
