name: Deploy to GitHub pages

on:
  push:
    branches:
      - main
      - TiNa
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  Lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repo
        uses: actions/checkout@v4

      - name : Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: fix lint
        run: npm run lint --fix

      - name: Run Linter
        run: npm run lint



  Test:
    name: Test
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run Test
        run: npm run test

#      - name: Tests E2E
#        uses: cypress-io/github-action@v6

  Build:
    name: Build
    needs:
     - Lint
     - Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

